# https://taskfile.dev

version: '3'

tasks:
  init:
    cmds:
      - git config --local core.hooksPath .githooks/
  build:
    cmds:
      - dotnet build
  test:
    deps: [build]
    cmds:
      - dotnet test --no-build
  rebuild:
    cmds:
      - dotnet clean
      - dotnet build-server shutdown
      - dotnet build