using System;

namespace Xabbo.Core
{
    public enum DisconnectReason
    {
        NotDisconnected = -2147483647,
        UnknownReason = -1,
        MaintenanceBreak = -2,
        Disconnected = -3,
        ConnectionFailed = -4,
        SocketDisconnect = -5,
        SocketTimeout = -6,
        ClientClosing = -7,
        ReselectServer = -8,
        ChangeAvatar = -9,
        CreateAvatar = -10,
        Logout = 0,
        JustBanned,
        ConcurrentLogin,
        ConnectionLostToPeer,
        AvatarIdentityChange,
        RemoveFurnitureTool,
        StillBanned = 10,
        DualLoginByAvatarId,
        HotelClosed,
        DualLoginByIp,
        PeerConnectionMissing = 16,
        NoLoginPermission,
        DuplicateConnection,
        HotelClosing,
        IncorrectPassword,
        InvalidToken,
        InvalidLoginTicket,
        VersionCheckUrl,
        VersionCheckProperty,
        VersionCheckMachineId,
        NoMessengerSession,
        UserNotFound,
        CryptoNotInitializedOld,
        DevCryptoNotAllowedOld,
        CryptoNotInitialized = 50,
        DevCryptoNotAllowed,
        CryptoReinitialization,
        PublicKeyNotNumeric,
        PublicKeyTooShort,
        CryptoMitmAttack,
        DuplicateUuidDetected = 100,
        OldSessionInProxy,
        PublicKeyNotNumericOld,
        PublicKeyTooShortOld,
        SocketReadGeneric,
        SocketReadFirstByte,
        SocketReadLength,
        SocketReadBody,
        SocketReadPolicy,
        SocketIoException,
        SocketWrongCrypto,
        ProxyRuntimeException,
        IdleConnection,
        PongTimeout,
        IdleConnectionNotAuth,
        IdleConnectionNoAvatarId,
        WriteClosedChannel,
        SocketWriteException1,
        SocketWriteException2,
        SocketWriteException3,
        TooManyBytesPendingWrite,
        IdleConnectionPolicyRequest,
        IncompatibleClientVersion,
        CredentialsRemoved,
        InsufficientSecurityLevel,
        TooManyUndefinedClientMessages,
        InvalidParameterRange,
        ClientIpBlocked,
        TooManyMessagesPendingWrite,
        SocketWriteTimeout,
        VersionUpdateRequired
    }
}
